security:
    password_hashers:
        App\Entity\Usuario: plaintext
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface:
            algorithm: 'null'

    role_hierarchy:
        ROLE_ADMIN: ROLE_USER
        ROLE_SUPER_ADMIN: ROLE_ADMIN

    providers:
        user_db:
            entity: { class: App\Entity\Usuario, property: codigoUsuarioPk }

    firewalls:
        main:
            pattern: /.*
            provider: user_db
            form_login:
                login_path: /login
                check_path: /login
                remember_me: false
                default_target_path: /inicio
            logout:
                path: /logout
                target: /

    access_control:
        - { path: /login, roles: PUBLIC_ACCESS }
        - { path: /recuperarclave, roles: PUBLIC_ACCESS }
        - { path: /registro, roles: PUBLIC_ACCESS }
        - { path: ^/administrador/.*, roles: ROLE_ADMIN }
        - { path: /utilidad/.*, roles: PUBLIC_ACCESS }
        - { path: /cliente/.*, roles: ROLE_USER }
        - { path: /documental/.*, roles: ROLE_USER }
        - { path: /empleado/.*, roles: ROLE_USER }
        - { path: /empresa/.*, roles: ROLE_USER }
        - { path: /seguridad/.*, roles: ROLE_USER }
        - { path: /inicio, roles: ROLE_USER }